jewelrystore/jewelryapp/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("", views.index_view.index, name="index"),
    path('jewelry/', views.jewelry_list_view.JewelryListView.list_jewelry_filtered, name='jewelry'),
    path("jewelry/<int:pk>", views.jewelry_detail_view.JewelryDetailView.as_view(), name="jewelry_detail"),
    path("jewelry/add_to_cart/<int:pk>", views.jewelry_detail_view.add_to_cart, name="add_to_cart"),
    path("shoppingcart_detail/<int:pk>", views.shopping_cart_detail_view.ShoppingCartDetailView.as_view(), name="shoppingcart_detail"),
    path("shoppingcart_detail/clear_cart/<int:pk>", views.shopping_cart_detail_view.clear_cart, name="clear_cart"),
    path('orders/', views.order_list_view.OrderListView.as_view(), name='orders'),
    path("order/<int:pk>", views.order_detail_view.OrderDetailView.as_view(), name="order_detail"),
    path("order/place_order", views.shopping_cart_detail_view.place_order, name="place_order"),
]

jewelrystore/jewelrystore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
# Use static() to add url mapping to serve static
# files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jewelryapp/', include('jewelryapp.urls')),
    path('registration/', include('registration.urls')),
    path('', RedirectView.as_view(url='/jewelryapp/')),
    path('accounts/', include('django.contrib.auth.urls')),
]
# For static content.
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# For media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jewelrystore/jewelryapp/models/cart_item.py
from django.db import models
from django.urls import reverse
from datetime import date

from jewelryapp.models import ShoppingCart
from jewelryapp.models import Jewelry

class CartItem(models.Model):
    """Represents a jewelry item added to the shopping cart by the shopper"""

    shopping_cart = models.ForeignKey(
        ShoppingCart,
        on_delete = models.CASCADE,
        null=True,
    )

    # This is done instead of duplicating the data of a jewelry item inside
    # a cart item.
    jewelry_item = models.ForeignKey(Jewelry, on_delete=models.CASCADE, null=True, blank=True)

    count = models.IntegerField(default=1, editable=False, help_text="The number of jewelry items of the same type added to the shopping cart")

    total_price = models.DecimalField(default=0, max_digits=8, decimal_places=2, editable=False, help_text="The total price of this type of item. It's count multiplied by its unit price")

    def __str__(self):
        """Identifies the object"""
        return f"{self.shopping_cart.__str__()} {self.jewelry_item.__str__()} {self.id}"

    # Decided against providing an url to this item.
    # It could be used to view this cart item in detail by accessing the
    # jewelry's data. And then provide the user with the ability to remove it
    # from cart. Instead a link to the jewelry item will be provided instead
    # to view it in detail, without any special functionality.

jewelrystore/jewelryapp/models/jewelry.py
from django.db import models
from django.urls import reverse
from datetime import date
from PIL import Image

class Jewelry(models.Model):
    """Fully describes a type or piece of jewelry to the user."""

    # Unique name of the jewelry. Typically identifies the metals used,
    # gem stones used, and some other special names.
    title = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        help_text="Required. E.g. Stainless Steel Mixed Color Pendant")

    CATEGORIES = (
        ("e", "Earring"),
        ("r", "Ring"),
        ("n", "Necklace"),
        ("p", "Pendant"),
        ("b", "Braces"),
    )

    category = models.CharField(
        max_length=1,
        choices=CATEGORIES,
        blank=True,
        default='r',
        help_text='The type of jewelry this belongs to'
    )

    date_time_added = models.DateField(auto_now = True)

    # AED's, UAE Dirhams
    price = models.DecimalField(max_digits=8, decimal_places=2)

    GEMSTONES = (
        ("r", "Ruby"),
        ("d", "Diamond"),
        ("s", "Saphire"),
        ("j", "Jade"),
        ("p", "Pearl"),
        ("a", "Amethyst"),
    )

    # Jewelry are differentiated by the jewels used and the metals used.
    # This variable is needed to clearly communicate the type of jewel used
    # in the jewelry item and thus communicate its value to the potential
    # customer.
    gemstones_used = models.CharField(
        max_length=1,
        choices=GEMSTONES,
        blank=True,
        default='r',
        help_text='Gemstones, like ruby or saphire, used in this item'
    )

    METALS = (
        ("t", "Stainless Steel"),
        ("s", "Silver"),
        ("g", "Gold"),
        ("r", "Rose Gold"),
        ("p", "Platinum"),
    )

    # Jewelry are further differentiated by the type of metals they are made
    # from, not just the gem stones used. Silver, gold, or platinum all are
    # very important for jewelry.
    # This indicates what metals, if any, were used in the item, such as in
    # the handles or connectors.
    metallic_finish = models.CharField(
        max_length=1,
        choices=METALS,
        blank=True,
        default='t',
        help_text='Metal the jewelry is made from'
    )

    STATUS = (('o', 'Out of stock'), ('a', 'Available'),)

    availability = models.CharField(
        max_length=1,
        choices=STATUS,
        blank=True,
        default='a',
        help_text='Availability for purchase'
    )

    # A small image that shows the jewelry for list views.
    thumbnail = models.ImageField(null=True, upload_to="jewelry-gallery")

    # A larger image of the jewelry item to show more detail for the customer.
    # Without null = True, django will complain about non-nullable field.
    detail_image = models.ImageField(null=True, upload_to="jewelry-gallery")

    def __str__(self):
        """Identifies the object"""
        return f"{self.title}"

    def get_absolute_url(self):
        """Returns url to detail page of the jewelry"""
        return reverse("jewelry_detail", args = [str(self.id)])

jewelrystore/jewelryapp/models/order.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Order(models.Model):
    """Keeps track of the items that the shopper ordered"""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        help_text="The user that placed the order. I.e. The shopper.",
    )

    total_price = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2,
        editable=False,
        help_text="The total price of all items ordered by this order instance"
    )

    date_time_created = models.DateTimeField(
        auto_now_add=True,
        help_text="The date and time when the order was placed"
    )

    def __str__(self):
        """Identifies the object"""
        return f"{self.user.username} Order No.{self.id}"

    def get_absolute_url(self):
        """Returns url to this order for checking"""
        return reverse("order_detail", args = [str(self.id)])

jewelrystore/jewelryapp/models/order_item.py
from django.db import models
from django.urls import reverse
from datetime import date

from jewelryapp.models import Order
from jewelryapp.models import Jewelry

class OrderItem(models.Model):
    """Represents one or more jewelry items of the same type ordered by the user"""

    order = models.ForeignKey(
        Order,
        on_delete = models.CASCADE,
        null=True,
    )

    # This is done instead of duplicating the data of a jewelry item
    jewelry_item = models.ForeignKey(Jewelry, on_delete=models.CASCADE, null=True, blank=True,)

    count = models.IntegerField(default=1, editable=False, help_text="The number of jewelry items of the same type ordered")

    total_price = models.DecimalField(default=0, max_digits=8, decimal_places=2, editable=False, help_text="The total price of this type of item. It's count multiplied by its unit price")

    def __str__(self):
        """Identifies the object"""
        return f"{self.order.__str__()} {self.jewelry_item.__str__()} {self.id}"

jewelrystore/jewelryapp/forms/profile_detail_form.py
from django.forms import ModelForm
from jewelryapp.models import Profile

class ProfileDetailModelForm(ModelForm):
    class Meta:
        model = Profile
        fields = ["birth_date", "phone_number", "delivery_address"]

jewelrystore/jewelryapp/forms/user_detail_form.py
from django.forms import ModelForm
from jewelryapp.models import User

class UserDetailModelForm(ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

jewelrystore/jewelryapp/views/activate_view.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from jewelryapp.tokens import account_activation_token

# Activates accounts for users that have completed email-verification for
# sign up. It also adds the user to the group of customers.
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()

        login(request, user)
        return redirect('index')
    else:
        return render(request, 'account_activation_invalid.html')

jewelrystore/jewelryapp/views/index_view.py
from django.shortcuts import render
import datetime

def index(request):
    date_today = datetime.datetime.now()

    context = {
        'date_today': date_today,
    }

    return render(request, "index.html", context = context)

jewelrystore/jewelryapp/views/jewelry_detail_view.py
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import F

from jewelryapp.models import Jewelry, CartItem, ShoppingCart

class JewelryDetailView(generic.DetailView):
    model = Jewelry

def add_to_cart(request, pk):
    jewelry = get_object_or_404(Jewelry, pk=pk)
    shopping_cart = request.user.shoppingcart
    # If this type of jewelry item already exists in the shopping cart then
    # do not create a new one, just increment its count in the cart item.
    cart_items = shopping_cart.cartitem_set.all()
    specific_cart_item = cart_items.filter(jewelry_item=jewelry)

    if specific_cart_item:
        specific_cart_item.update(count=F('count') + 1)
        specific_cart_item.update(total_price=F('total_price') + jewelry.price)
    else:
        new_cart_item = CartItem(
            shopping_cart=shopping_cart,
            jewelry_item=jewelry,
            total_price=jewelry.price,
        )
        new_cart_item.save()

    # Increment the total price for the shopping cart as a whole
    ShoppingCart.objects.filter(id=request.user.shoppingcart.id).update(total_price=F('total_price') + jewelry.price)

    return HttpResponseRedirect(reverse('jewelry_detail', args=(pk,)))

jewelrystore/jewelryapp/views/jewelry_list_view.py
from django.views import generic
from django.shortcuts import render

from jewelryapp.models import Jewelry
from jewelryapp.filters import JewelryFilter

class JewelryListView(generic.ListView):
    model = Jewelry
    paginate_by = 10

    def list_jewelry_filtered(request):
        sorting_attr="date_time_added"
        jewelry_filter = JewelryFilter(request.GET, queryset=Jewelry.objects.all())
        return render(
            request,
            'jewelryapp/jewelry_list.html',
            {'filter': jewelry_filter, 'sorting_attr': sorting_attr,}
        )

jewelrystore/jewelryapp/views/order_detail_view.py
from django.views import generic

from jewelryapp.models import Order
from jewelryapp.models import OrderItem

class OrderDetailView(generic.DetailView):
    model = Order

jewelrystore/jewelryapp/views/order_list_view.py
from django.views import generic

from jewelryapp.models import Order

class OrderListView(generic.ListView):
    model = Order
    paginate_by = 10

jewelrystore/jewelryapp/views/shopping_cart_detail_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.urls import reverse
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.db.models import F

from jewelryapp.models import ShoppingCart, Order, OrderItem

class ShoppingCartDetailView(generic.DetailView):
    login_url = 'login'
    redirect_field_name = 'redirect_to'
    model = ShoppingCart

def clear_cart(request, pk):
    """Resets the shopping cart so the past items do not
    interfere with future orders by the user"""

    request.user.shoppingcart.cartitem_set.all().delete()
    ShoppingCart.objects.filter(id=request.user.shoppingcart.id).update(total_price=0)

    return HttpResponseRedirect(reverse('shoppingcart_detail', args=(pk,)))

def place_order(request):
    """Helps users and the business keep track of the shopper's orders"""

    # Create a new order
    new_order = Order(user=request.user)
    new_order.save()
    new_order.refresh_from_db()

    # Used to compute the total price of all the ordered items
    # Needed to set the placed order's total price
    total_price = 0

    # Create new order items out of the cart items to populate the new order.
    cart_items = request.user.shoppingcart.cartitem_set.all()

    for item in cart_items:
        new_order_item = OrderItem(
            order=new_order,
            jewelry_item=item.jewelry_item,
            count=item.count,
            total_price=item.total_price,
        )
        new_order_item.save()
        total_price += item.total_price

    # The order's total price is not set automatically
    Order.objects.filter(id=new_order.id).update(total_price=F('total_price') + total_price)

    # Delete the shopping cart's contents. I.e. Clear it of its cart items.
    request.user.shoppingcart.cartitem_set.all().delete()

    return HttpResponseRedirect(reverse('order_detail', args=(new_order.id,)))

jewelrystore/jewelryapp/views/signup_view.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string

from jewelryapp.forms import SignUpForm
from jewelryapp.tokens import account_activation_token

# Creates a new user. Only customer users are created. Admin or staff users, are
# created by another admin or super user through the admin site or the admin
# portion of this site.
def signup(request):
    """Create a new unactivated user in the db for a potential new user."""
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # This is needed to force the user to rely on the email
            # confirmation. Otherwise, the user can log in without the
            # confirmation email.
            user.is_active = False
            # user_name = f"{user.first_name}_{user.last_name}"
            # Creates new user object in the database.
            user.save()

            # Load the profile instance created by the signal
            # Needed to save the profile details of the user.
            user.refresh_from_db()
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.profile.phone_number = form.cleaned_data.get('phone_number')
            user.profile.delivery_address = form.cleaned_data.get('delivery_address')
            # Save again, to save the new changes made to the user's profile
            user.save()

            # Without this the user will not belong to any group.
            # Newly signed up users can only be customers. Otherwise, they have
            # to have an account created to them by the admin/staff manually.
            group = Group.objects.get(name="Customers")
            group.user_set.add(user)

            current_site = get_current_site(request)
            subject = 'Activate Your JewelryApp Account'
            message = render_to_string('account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)

            return redirect("account_activation_sent")
    else:
        form = SignUpForm()

    return render(request, 'signup.html', {'form': form})

jewelrystore/jewelryapp/templates/jewelryapp/jewelry_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>{{ jewelry.title }}</h1>

    <p>
        Type: {{ jewelry.get_category_display }}
    </p>

    <p>
        Gemstones: {{ jewelry.get_gemstones_used_display }}
    </p>

    <p>
        Metals: {{jewelry.get_metallic_finish_display}}
    </p>

    <p>
        Availability: {{jewelry.get_availability_display}}
    </p>

    <p>
        Price: {{jewelry.price}}
    </p>

    <p>
        <img src="{{ jewelry.detail_image.url }}" alt="{{jewelry.title}}"
        width="360" height = "240">
    </p>

    <!-- Add to my cart button should be here -->
    {% if user.is_authenticated %}
    <form action="{% url 'add_to_cart' pk=jewelry.id %}" method="GET">
        {% csrf_token %}
        <button type="submit">Add to Cart</button>
    </form>
    {% else %}
        <p>
            <a href="{% url 'login' %}?next={{request.path}}">
                Sign in to add item to your cart
            </a>
        </p>
    {% endif %}
{% endblock %}

jewelrystore/jewelryapp/templates/jewelryapp/jewelry_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Jewelry</h1>

    <form action="" method="get">
        <h2>Filter Results</h2>
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    
    <h2>Results</h2>
    {% for obj in filter.qs %}
        <li>
            <a href="{{ obj.get_absolute_url }}">
                <p>
                    <img src="{{ obj.thumbnail.url }}"
                    alt="Small image of {{obj.title}}"
                    width="120" height = "80">
                </p>
                <p>{{ obj.title }}</p>
            </a>
        </li>
    {% endfor %}
{% endblock %}

jewelrystore/jewelryapp/templates/jewelryapp/old_stuff.html
<form action="{% url 'add_to_cart' pk=jewelry.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit">Add to Cart</button>
</form>
<p>
    <a href='{% url 'add_to_cart' %}'>Add to Cart</a>
</p>

<form action="" method="post">
    <input type="submit" value="Clear Cart">
</form>


def add_to_cart(request, pk):
jewelry = get_object_or_404(Jewelry, pk=pk)
new_cart_item = CartItem(
    shopping_cart=request.user.shoppingcart,
    jewelry_item=jewelry
)
new_cart_item.save()
return render(request, 'jewelryapp/jewelry_detail.html')

jewelrystore/jewelryapp/templates/jewelryapp/order_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My Order</h1>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Ordered Items</h4>

        {% if order.orderitem_set.exists %}
        <table>
            <theader>
                <tr>
                    <th>Quantity</th>
                    <th>Product Image</th>
                    <th>Product Name</th>
                    <th>Unit Price</th>
                    <th>Total Price</th>
                </tr>
            </theader>
            <tbody>
                {% for orderitem in order.orderitem_set.all %}
                <tr>
                    <td>{{ orderitem.count }}</td>
                    <td>
                        <a href="{{ orderitem.jewelry_item.get_absolute_url }}">
                        <img src="{{ orderitem.jewelry_item.thumbnail.url }}"
                        width="120" height = "80">
                        </a>
                    </td>
                    <td>
                    <a href="{{ orderitem.jewelry_item.get_absolute_url }}">
                        {{ orderitem.jewelry_item.title }}
                    </a>
                    </td>
                    <td>{{ orderitem.jewelry_item.price }}</td>
                    <td>{{ orderitem.total_price }}</td>
                </tr>
                {% endfor %}
            </tbody>
            <tfooter>
                <tr>
                    <th>Total</th>
                    <td>{{ order.total_price }}</td>
                </tr>
            </tfooter>
        </table>
        {% else %}
        <p>There are no ordered items.</p>
        {% endif %}
    </div>
{% endblock %}

jewelrystore/jewelryapp/templates/jewelryapp/order_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My Orders</h1>
    {% if user.order_set.all %}
        {% for order in user.order_set.all %}
            <li>
                <a href="{{ order.get_absolute_url }}">
                    <p>{{ order }} - placed on {{ order.date_time_created }}</p>
                </a>
            </li>
        {% endfor %}
    {% else %}
    <p>You don't have any placed orders.</p>
    {% endif %}
{% endblock %}

jewelrystore/jewelryapp/templates/jewelryapp/shoppingcart_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My Cart</h1>
    {% if shoppingcart.cartitem_set.exists %}
    <form action="{% url 'clear_cart' pk=shoppingcart.id %}" method="GET">
        {% csrf_token %}
        <button type="submit">Clear Cart</button>
    </form>
    <form action="{% url 'jewelry' %}" method="GET">
        {% csrf_token %}
        <button type="submit">Back to Shopping</button>
    </form>
    <form action="{% url 'place_order' %}" method="GET">
        {% csrf_token %}
        <button type="submit">Place Order</button>
    </form>
    <table>
        <theader>
            <tr>
                <th>Quantity</th>
                <th>Product Image</th>
                <th>Product Name</th>
                <th>Unit Price</th>
                <th>Total Price</th>
            </tr>
        </theader>
        <tbody>
            {% for cartitem in shoppingcart.cartitem_set.all %}
            <tr>
                <td>{{ cartitem.count }}</td>
                <td>
                    <a href="{{ cartitem.jewelry_item.get_absolute_url }}">
                    <img src="{{cartitem.jewelry_item.thumbnail.url}}"
                    width="120" height = "80">
                    </a>
                </td>
                <td>
                <a href="{{ cartitem.jewelry_item.get_absolute_url }}">
                    {{ cartitem.jewelry_item.title }}
                </a>
                </td>
                <td>{{ cartitem.jewelry_item.price }}</td>
                <td>{{ cartitem.total_price }}</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfooter>
            <tr>
                <th>Total</th>
                <td>{{ shoppingcart.total_price }}</td>
            </tr>
        </tfooter>
    </table>
    {% else %}
    <p>There are items in your cart.</p>
    {% endif %}
{% endblock %}